### ISSUE TITLE
Install on Unix like OS assumes bash shell environment

### ISSUE THREAD

**Issue by dibdotdob** [angoca/log4db2#191]
Hi Andres, sourcing the install script fails if the current shell isn't bash.   I use ksh for my shell, so the install script fails as the "local" function isn't part of ksh.   Can the documentation be updated to reflected this.  Longer term, a portable script would be better.

**Comment by angoca** [comment]
Scripts now work with Bash or Korn, first because there is not a shebang at the beginning, and because they do not have any bashism.
